from sqlalchemy import Column, Integer, String, BigInteger, Float, DateTime, JSON, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()

class PerformanceData(Base):
    __tablename__ = 'performance_data'
    
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, nullable=False)
    modified_at = Column(DateTime, nullable=False)
    clicks = Column(BigInteger)
    conversions = Column(Float)
    conversions_values = Column(Float)
    cost_per_conversions = Column(Float)
    cpc = Column(Float)
    cpm = Column(Float)
    ctr = Column(Float)
    date = Column(String(20))
    impressions = Column(BigInteger)
    campaign_id = Column(BigInteger, ForeignKey('campaigns.id'))
    action_values = Column(JSON)
    actions = Column(JSON)
    catalog_segment_value = Column(JSON)
    checkout = Column(Float)
    converted_product_quantity = Column(JSON)
    converted_product_value = Column(JSON)
    cost_per_ad_click = Column(JSON)
    cost_per_app_install = Column(Float)
    cost_per_checkout = Column(Float)
    cost_per_dda_countby_convs = Column(Float)
    cost_per_lauch_app = Column(Float)
    cost_per_purchase = Column(Float)
    cost_per_search = Column(Float)
    cost_per_total_checkout = Column(Float)
    cost_per_total_purchase = Column(Float)
    dda_countby_convs = Column(Float)
    mobile_app_purchase_roas = Column(JSON)
    purchase = Column(Float)
    purchase_rate = Column(Float)
    purchase_roas = Column(JSON)
    real_time_conversion = Column(Float)
    real_time_conversion_rate = Column(Float)
    real_time_cost_per_conversion = Column(Float)
    search = Column(Float)
    total_actove_pay_roas = Column(Float)
    total_checkout = Column(Float)
    total_checkout_value = Column(Float)
    total_purchase = Column(Float)
    total_purchase_value = Column(Float)
    value_per_checkout = Column(Float)
    value_per_total_purchase = Column(Float)
    video_viewsp100 = Column(Float)
    video_viewsp75 = Column(Float)
    website_purchase_roas = Column(JSON)
    ad_id = Column(BigInteger, ForeignKey('ad.id'))
    onsite_web_purchase_value = Column(Float)
    purchase_value = Column(Float)
    purchase_count = Column(BigInteger)
    add_to_cart_value = Column(Float)
    onsite_web_add_to_cart_count = Column(BigInteger)
    
    # Establish relationships
    campaign = relationship("Campaign")
    ad = relationship("Ad")
